### ISSUE TITLE
Infinite next

### ISSUE THREAD

**Issue by kathy-tam** [SarahAvery/srcful#132]
- You can keep clicking next (/pages/infinite)
- Next button should disappear after the last resource

**Comment by SarahAvery** [comment]
I am not going to worry about this. I though about it yesterday, and decided that it was too out of scope for this project. 
You would have to get all the resources, count them, then have an end number, then dividing that by how many limit per page, then fetching again to have the right number of pages populate... It is a whole mess that I and we, should not concern ourselves with right now. Pagination in itself is a very difficult thing to do properly, and we are just barely getting by with a hack.
